### PR TITLE
fix: prevent fallback icon infinite loop

### LINKED ISSUE #4237: [🐛 Bug]:  non stop requests for get icon
I have few custom providers without icon
When I update keephq to 0.40.7 version I have bug with non stop requests for icon image.
When I want set icon image I haven't choice for zabbixcustom and dynatracecustom (look to screen)

Image

Image

### PR DESCRIPTION
**Pull request by 35C4n0r**
Closes #4237 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

File: keep-ui/shared/api/ApiClient.ts [hunk 1]
```diff
@@ -48,6 +48,7 @@ export class ApiClient {
     }
     return {
       Authorization: `Bearer ${this.session.accessToken}`,
+      "ngrok-skip-browser-warning": true,
```
Comment (talboren) [inline keep-ui/shared/api/ApiClient.ts:51]: ?

Comment (35C4n0r) [reply keep-ui/shared/api/ApiClient.ts:51]: This is to prevent getting the warning page you get from the ngrok (if frontend is not on localhost). So instead of getting API response you get a HTML document as a response on the frontend, I always kept a patch for it on my local, it would be nice if we can get this merged.

**Review by talboren — APPROVED** [review]
